// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6fXMhF5ZYSQmnqSfZsGeDuqj_Nv9QNPs',
    appId: '1:792888586324:web:6ad965b04455dd0819bdc1',
    messagingSenderId: '792888586324',
    projectId: 'datafirebase-94d8a',
    authDomain: 'datafirebase-94d8a.firebaseapp.com',
    storageBucket: 'datafirebase-94d8a.appspot.com',
    measurementId: 'G-PMSY4KMTLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClt7aDBwtcP_18EL1HufFJdfkIplILLTY',
    appId: '1:792888586324:android:bc39668bd890e9b919bdc1',
    messagingSenderId: '792888586324',
    projectId: 'datafirebase-94d8a',
    storageBucket: 'datafirebase-94d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxGjW9Orqm92CpJmEc_fGcCwn5s3iI1w',
    appId: '1:792888586324:ios:0ce8f6ad2e00725c19bdc1',
    messagingSenderId: '792888586324',
    projectId: 'datafirebase-94d8a',
    storageBucket: 'datafirebase-94d8a.appspot.com',
    iosBundleId: 'com.example.personalHealthManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxGjW9Orqm92CpJmEc_fGcCwn5s3iI1w',
    appId: '1:792888586324:ios:0ce8f6ad2e00725c19bdc1',
    messagingSenderId: '792888586324',
    projectId: 'datafirebase-94d8a',
    storageBucket: 'datafirebase-94d8a.appspot.com',
    iosBundleId: 'com.example.personalHealthManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6fXMhF5ZYSQmnqSfZsGeDuqj_Nv9QNPs',
    appId: '1:792888586324:web:7e9df381d905586019bdc1',
    messagingSenderId: '792888586324',
    projectId: 'datafirebase-94d8a',
    authDomain: 'datafirebase-94d8a.firebaseapp.com',
    storageBucket: 'datafirebase-94d8a.appspot.com',
    measurementId: 'G-2MKJHB4W57',
  );
}
